### Matrix multiplication -  m*n arrays
https://www.programiz.com/python-programming/examples/multiply-matrix

In [13]:
import numpy as np
def MatrixMultiplication(A, B):
    m = A.shape[0]
    n = B.shape[1]
    s = B.shape[0]
    C = np.zeros(shape=(m,n))
    for i in range(m):
        for j in range(n):
            #print(C)
            for k in range(s):
                C[i,j] += A[i,k] *  B[k,j]
                #print(A[i,k],B[k,j] ,C[i,j])
    return C

In [16]:
A = np.array([[2,3,5,12],[8,3,2,3],[1,9,0,6],[11,95,20,56],[1,99,320,16],[21,9,0,1]])
B = np.array([[7,4,1],[18,5,20],[12,90,3],[11,290,22]])
#print(A)
#print(B)
print(MatrixMultiplication(A, B))

[[  260.  3953.   341.]
 [  167.  1097.   140.]
 [  235.  1789.   313.]
 [ 2643. 18559.  3203.]
 [ 5805. 33939.  3293.]
 [  320.   419.   223.]]


In [17]:
#print(A*B) print(np.multiply(A,B)) - dont use this for matrix multiplication
print(np.dot(A,B)) #matrix multiplication using  numpy

[[  260  3953   341]
 [  167  1097   140]
 [  235  1789   313]
 [ 2643 18559  3203]
 [ 5805 33939  3293]
 [  320   419   223]]
